In [ ]:
import numpy as np
array=np.array([[10,20,30],[60,70,90],[100,101,102]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.T)

2
(3, 3)
9
[[ 10  60 100]
 [ 20  70 101]
 [ 30  90 102]]


In [ ]:
array=np.arange(1,1000)
print(array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [ ]:
a=np.array([16,17,18],[10,20,30])
b=np.array([12,19,20],[50,60,70])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [66 77 88]
Subtraction: [-34 -43 -52]
Multiplication: [ 800 1020 1260]
Division: [0.32       0.28333333 0.25714286]
Floor Division: [0 0 0]
Modulus: [16 17 18]
Power: [256 289 324]


In [ ]:
array=np.array([1,2,3])
print("mean:",np.mean(array))

mean: 2.0


In [ ]:
array=np.array([100,20,30])
print("median:",np.median(array))

median: 30.0


In [ ]:
array=np.array([1,2,])
print("square:",np.square(array))

square: [ 1  4 49]


In [3]:
import numpy as np
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
print("\nSquare Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
print("\nExponential:", np.exp(arr))
print("\nNatural Log:", np.log(arr))
print("Log Base 10:", np.log10(arr))
print("\nSine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
print("Ceiling:", np.ceil(decimal))
print("Floor:", np.floor(decimal))

Original Array: [ 1  4  9 16 25]

Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Cube: [    1    64   729  4096 15625]

Absolute Value: [ 5 10 15 20 25]

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]

Natural Log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log Base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tangent: [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [8]:
import numpy as np
marks = np.array([42, 22, 15, 45, 25, 30, 69])

print("Original Array:", marks)
print("Sorted Array:", np.sort(marks))
print("\nSum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Range:", np.ptp(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))
print("25th Percentile:", np.percentile(marks, 25))
print("30th Percentile:", np.percentile(marks, 30))
print("69th Percentile:", np.percentile(marks, 69))

Original Array: [42 22 15 45 25 30 69]
Sorted Array: [15 22 25 30 42 45 69]

Sum: 248
Mean: 35.42857142857143
Median: 30.0
Maximum: 69
Minimum: 15
Range: 54
Standard Deviation: 16.893423427536554
Variance: 285.38775510204084
Index of Maximum: 6
Index of Minimum: 2
25th Percentile: 23.5
30th Percentile: 24.4
69th Percentile: 42.42


In [9]:
import numpy as np
print(np.random.rand())
print(np.random.rand(10))
print(np.random.randint(4, 60, 5))
subjects = ["DBMS", "Python", "Java", "AIML"]
print(np.random.choice(subjects))
print(np.random.normal(20, 10, 30))
print(np.random.uniform(10, 20, 30))
print(np.random.binomial(1, 0.5))
print(np.random.binomial(10, 0.7))
print(np.random.poisson(2, 3))
print(np.random.exponential(9, 6))

0.9189174974806217
[0.54586347 0.78668867 0.29752073 0.16501884 0.40944352 0.9850297
 0.72358269 0.33850128 0.72535784 0.80782287]
[12 11 15 22 26]
Python
[  9.40499122  24.44733731  20.77129339  28.4243754    5.85857756
  -4.23365648   4.90037058   4.79461989  17.57332192  15.51196829
  23.38618337  16.32018455  23.41489833  10.26623172  13.99290406
  24.75191967   9.2658154  -11.53940589  17.12507583  17.629193
  11.88026168  20.0863645   37.37796985  10.78099303  29.3265202
  34.7506189   20.52741263  29.03091833   7.7025949   17.2526382 ]
[16.30151243 16.77295243 15.20232055 13.59413829 19.61625249 14.59095536
 10.5018763  17.45204483 12.84697934 11.46381517 13.53007422 18.80315181
 17.98553837 18.22035066 19.23687479 16.59418921 11.26706497 10.04179394
 11.10757538 16.18886042 17.52175335 19.53439065 14.69088547 12.97687594
 11.39492539 11.98751451 17.19494849 19.76413567 10.54385194 10.80165613]
1
8
[3 2 5]
[16.67967296  3.7385715   3.11301714 26.96857613 16.86132305  1.04161459]